### ISSUE TITLE
Failure open terminal console after upgrade to 3.10.1

### ISSUE THREAD

**Issue by hanc2006** [cdr/code-server#3417]
## OS/Web Information

- Web Browser: Brave 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)
- Local OS: Ubuntu 20.04.2 LTS
- Remote OS: Ubuntu 20.04.2 LTS
- Remote Architecture: VM
- `code-server --version`: 3.10.1 421237f499079cf88d68c02163b70e2b476bbb0d

## Steps to Reproduce

1. Open a new terminal

## Expected

New terminal shell available

## Actual

No terminal

## VSCode settings
`"terminal.integrated.shell.linux":  "/usr/bin/zsh"`
Even commenting the configuration doesn't work

## Logs

Browser console

```
Uncaught TypeError: stack.split is not a function
    at handleCustomError (<anonymous>:8:27)
    at <anonymous>:27:4
```

```
ERR Invalid call '$getShellEnvironment': Error: Invalid call '$getShellEnvironment'
    at E.call (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:35:44245)
    at f.onPromise (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:15:58669)
    at f.onRawMessage (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:15:58028)
    at /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:15:57281
    at v.fire (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:10:1836)
    at w.fire (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:16:15361)
    at P._receiveMessage (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:16:20611)
    at /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:16:17505
    at v.fire (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:10:1836)
    at c.acceptChunk (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:16:12726)
    at /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:16:12074
    at v.fire (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:10:1836)
    at /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:35:89962
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:585:8)
```

**Comment by jsjoeio** [comment]
Unfortunately, I am not able to reproduce locally using macOS + Brave.

## Screenshot
<img width="1792" alt="Screen Shot 2021-05-19 at 10 49 34 AM" src="https://user-images.githubusercontent.com/3806031/118860198-f5497c00-b88f-11eb-9b88-747bb8c96f6f.png">

Can you try disabling all extensions and resetting your VS Code settings and see if you still get this error?

**Comment by hanc2006** [comment]
After restarting the service, the issue disappear! Thks
