### PR TITLE
Support browsers from before 2020

### PR DESCRIPTION
**Pull request by L3P3**
As reported in #2825, #2826 and #3051, almost everything works in older browsers. This setting here prevented me from updating and I think it is an obvious enhancement to not artificially restrict to browsers from 2020+. There should not be any noticable downsides of this change since es6 and es2020 are pretty similar with only minor differences.

### CODE REVIEW

**Comment by jawnsy** [comment]
I guess [upstream vscode uses es2020 as the target](https://github.com/microsoft/vscode/blob/13c0ed811e7e6bf2a961b2ab8b6d086fa7822fb4/src/tsconfig.json#L8), so one risk is that divergence means that the result may not be as well-tested. I don't know enough to have an accurate assessment of the risk though.

**Comment by jsjoeio** [comment]
> I guess upstream vscode uses es2020 as the target, so one risk is that divergence means that the result may not be as well-tested. I don't know enough to have an accurate assessment of the risk though.

Great point! I'm guessing we decided to use `es2020` after they upgraded. Looks like they dropped support for legacy edge and IE when they made [that upgrade](https://github.com/microsoft/vscode/issues/121144).

**Comment by code-asher** [comment]
We can change our target but code-server will still not work since VS
Code has their own target.  I am not sure we even have any of our own
client-side JavaScript anymore in 4.0.0.

**Comment by jsjoeio** [comment]
> We can change our target but code-server will still not work since VS
Code has their own target.  

Ah right! This would have to be in VS Code itself (or in [our fork](https://github.com/cdr/vscode)). But if we change in our fork, that would diverge from upstream and could cause other issues.

> I am not sure we even have any of our own
client-side JavaScript anymore in 4.0.0.

Wow, you're right. I didn't even realize that.

**Comment by L3P3** [comment]
As stated, between es6 and es2020, there are no interoperability risks. In this case, they only differ in syntactic sugar. Not even polyfills required to ensure compatiblity between two modules.
Isn't this tsconfig also respected in submodules? I think it should be at least tested if that works. Or are you sure that there will still be es2020 code after this proposed change?

**Comment by L3P3** [comment]
> I am not sure we even have any of our own client-side JavaScript anymore in 4.0.0.

What about the forked repository? Isn't that deemed "our own"?

**Comment by code-asher** [comment]
VS Code is compiled separately using their build process so our tsconfig
has no effect on it.

But if we patch it there instead and everything works that seems like a
win to me.

We could also leave this change here as well in case we ever add
client-side JavaScript again.

Our tests are reporting the following with this change:

```
  test/unit/node/cli.test.ts:91:11 - error TS2550: Property 'flat' does not exist on type '(string | string[])[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later
```

So maybe we also need to add `lib`.

**Comment by L3P3** [comment]
> So maybe we also need to add `lib`.

Yes, sure. Those are polyfills so that beside syntax change, also new methods work in older browsers. :wink:

**Comment by jsjoeio** [comment]
> But if we patch it there instead and everything works that seems like a
win to me.

Good point! I agree. @code-asher should we ask @L3P3 to submit a PR to our fork [here](https://github.com/cdr/vscode/blob/main/src/tsconfig.json#L8)?

> We could also leave this change here as well in case we ever add
client-side JavaScript again.

Agreed. As long as the build passes, I think we're okay to merge.

**Review by jsjoeio — APPROVED** [review]
Even though we don't have any client-side JS in code-server at the moment, we're okay merging this in, in case we do want to support older browser in the future.

Thanks @L3P3 for adding this 👍

**Comment by jsjoeio** [comment]
> Docs preview

P.S. you can ignore this. It's a known issue that I need to fix.

**Comment by L3P3** [comment]
Sounds great. Done.

**Comment by L3P3** [comment]
BTW if anyone wonders why they targeted es2020 in the first place: They use electron which is pretty much latest chrome. Web development and electron development has some differences. :wink:

**Comment by jsjoeio** [comment]
```javascript
FAIL test/unit/node/routes/login.test.ts
  ● Test suite failed to run

    test/unit/node/routes/login.test.ts:81:9 - error TS2322: Type 'URLSearchParams' is not assignable to type 'BodyInit | undefined'.
      Type 'URLSearchParams' is missing the following properties from type 'URLSearchParams': entries, keys, values, [Symbol.iterator]

    81         body: params,
               ~~~~
```

Hmm... looks like one of the tests are failing. You might need to look into fixing `login.test.ts`

**Comment by jsjoeio** [comment]
I still see the same error in the test [here](https://github.com/cdr/code-server/runs/4462927946?check_suite_focus=true#step:9:548). We'll push this for the next release.

**Comment by L3P3** [comment]
Sorry, I thought that dom includes dom.iterable but it appears to not be the case. Just another try and hopefully no error. :see_no_evil:
